import {
  TeamInfoWrapper,
  TeamInfo,
  TeamInfoHeader,
  TeamName,
  Team,
  UserInfoColumnWrapper,
  UserInfoColumn,
  PlayerList,
} from '../styles/teamInfoContainer.s';
import Summoner from './Summoner';

const TeamInfoContainer = () => {
  return (
    <TeamInfoWrapper>
      <TeamInfo>
        <TeamInfoHeader>
          <TeamName team={Team.RED}>RED TEAM</TeamName>
          <UserInfoColumnWrapper>
            <UserInfoColumn>SUMMONER</UserInfoColumn>
            <UserInfoColumn>ITEMS</UserInfoColumn>
          </UserInfoColumnWrapper>
        </TeamInfoHeader>
        <PlayerList>
          <Summoner
            champion={'Sona'}
            championSpell1={'SummonerHeal'}
            championSpell2={'SummonerFlash'}
            item0={'3133'}
            item1={'6694'}
            item2={'3089'}
            item3={'3047'}
            item4={'3086'}
            item5={'3087'}
            item6={'3340'}
          />
          <Summoner
            champion={'Jax'}
            championSpell1={'SummonerDot'}
            championSpell2={'SummonerFlash'}
            item0={'3033'}
            item1={'3032'}
            item2={'3036'}
            item3={'3035'}
            item4={'3038'}
            item5={'3040'}
            item6={'3340'}
          />
          <Summoner
            champion={`Katarina`}
            championSpell1={'SummonerSmite'}
            championSpell2={'SummonerFlash'}
            item0={'3133'}
            item1={'6694'}
            item2={'3089'}
            item3={'3047'}
            item4={'3086'}
            item5={'3087'}
            item6={'3340'}
          />
          <Summoner
            champion={'Blitzcrank'}
            championSpell1={'SummonerBoost'}
            championSpell2={'SummonerFlash'}
            item0={'3033'}
            item1={'3032'}
            item2={'3036'}
            item3={'3035'}
            item4={'3038'}
            item5={'3040'}
            item6={'3340'}
          />
          <Summoner
            champion={'Brand'}
            championSpell1={'SummonerExhaust'}
            championSpell2={'SummonerFlash'}
            item0={'3133'}
            item1={'6694'}
            item2={'3089'}
            item3={'3047'}
            item4={'3086'}
            item5={'3087'}
            item6={'3340'}
          />
        </PlayerList>
      </TeamInfo>
      <TeamInfo>
        <TeamInfoHeader>
          <TeamName team={Team.BLUE}>BLUE TEAM</TeamName>
          <UserInfoColumnWrapper>
            <UserInfoColumn>SUMMONER</UserInfoColumn>
            <UserInfoColumn>ITEMS</UserInfoColumn>
          </UserInfoColumnWrapper>
        </TeamInfoHeader>
        <PlayerList>
          <Summoner
            champion={'Aphelios'}
            championSpell1={'SummonerTeleport'}
            championSpell2={'SummonerFlash'}
            item0={'3033'}
            item1={'3032'}
            item2={'3036'}
            item3={'3035'}
            item4={'3038'}
            item5={'3040'}
            item6={'3340'}
          />
          <Summoner
            champion={'Rumble'}
            championSpell1={'SummonerHeal'}
            championSpell2={'SummonerFlash'}
            item0={'3133'}
            item1={'6694'}
            item2={'3089'}
            item3={'3047'}
            item4={'3086'}
            item5={'3087'}
            item6={'3340'}
          />
          <Summoner
            champion={'Lux'}
            championSpell1={'SummonerDot'}
            championSpell2={'SummonerFlash'}
            item0={'3033'}
            item1={'3032'}
            item2={'3036'}
            item3={'3035'}
            item4={'3038'}
            item5={'3040'}
            item6={'3340'}
          />
          <Summoner
            champion={'Draven'}
            championSpell1={'SummonerHeal'}
            championSpell2={'SummonerFlash'}
            item0={'3133'}
            item1={'6694'}
            item2={'3089'}
            item3={'3047'}
            item4={'3086'}
            item5={'3087'}
            item6={'3340'}
          />
          <Summoner
            champion={'Nasus'}
            championSpell1={'SummonerHeal'}
            championSpell2={'SummonerFlash'}
            item0={'3033'}
            item1={'3032'}
            item2={'3036'}
            item3={'3035'}
            item4={'3038'}
            item5={'3040'}
            item6={'3340'}
          />
        </PlayerList>
      </TeamInfo>
    </TeamInfoWrapper>
  );
};

export default TeamInfoContainer;
